export const digreeOptions = [
  "Intermediate",
  "B.Tech (2 Years)",
  "B.Tech (3 Years)",
  "B.Tech (4 Years)",
  "Bachelors (2 Years)",
  "Bachelors (4 Years)",
  "Bachelors (5 Years)",
  "Masters",
  "MPHIL",
  "PHD",
];
export const degreeAreas = [
  "ACCA",
  "Acoustical Engineering",
  "Administrative Sciences",
  "Advertisment",
  "Aeronautics",
  "Aeronotical",
  "Aerospace Engineering",
  "Agriculture",
  "Agriculture Engineering",
  "Allied Sciences",
  "Analytical Chemistry",
  "Applied Mathematics",
  "Applied Mechanics",
  "Applied Optics",
  "Arabic",
  "Archeology",
  "Architectural Engineering and Design",
  "Architecture",
  "Astro-geology",
  "Astronautics",
  "Astronomy and Applied Sciences",
  "Astro-Physics",
  "Auto and Diesel",
  "Auto and Farm",
  "Automation",
  "Banking",
  "Bio Engineering",
  "Bio Medical",
  "Bio Medical Technology",
  "Biochemistry",
  "Biochemical Sciences",
  "Biological Anthropology",
  "Botanical Sciences",
  "Botany",
  "Business and Information Technology",
  "Business Administration (Finance)",
  "Business Administration (HRM)",
  "Business Administration (Management)",
  "Business Administration (Marketing)",
  "Business Administration (TQM)",
  "Business Economics",
  "CHARTERED ACCOUNTANT (CA)",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Cold Technology",
  "Commerce",
  "Computer Engineering",
  "Computer Science",
  "Criminology",
  "Crystallography",
  "Dental Technology",
  "Dentistry",
  "Dermatology",
  "Diagnostic Radiography",
  "Dietetics",
  "Dress Designing and Making",
  "Earth (Astronomical Geography)",
  "Earth Sciences",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Electronics",
  "Emergency and Intensive Care",
  "Engineering",
  "Engineering Economics",
  "Engineering Geology",
  "Engineering Meteorology",
  "English",
  "English Literature",
  "Environmental Sciences",
  "Environmental Control Technology",
  "Environmental Engineering",
  "Epidemiology",
  "Evolution and Genetics",
  "Experimental Medicine",
  "Finance",
  "Fine Arts",
  "Fisheries and Aquaculture",
  "Food Technology",
  "Forestry Engineering",
  "Foundry and Pattern Making",
  "Gender and Development Studies",
  "Gender Studies",
  "General Science",
  "Geography",
  "Geology Sciences",
  "Gynecology related medical Specialties",
  "History",
  "Home Economics",
  "Human anatomy, Cytology, Histology",
  "Human Physiology",
  "Human Resource Management",
  "Hydraulic Engineering",
  "Hydrology",
  "Imaging Diploma in Public Health Technology",
  "Incidence and Prevention of disease",
  "Industrial Engineering",
  "Information and Communication System Engineering",
  "Information System",
  "Information Technology",
  "Instrumentation",
  "Insurance and Risk Management",
  "Internal Medicine",
  "International Relations",
  "IR and Politics",
  "Islamiyat",
  "Journalism",
  "Lab Technology",
  "Law",
  "Library and Archival Sciences",
  "Management Information System",
  "Marine Sciences",
  "Marketing",
  "Mass Communication",
  "Mathematical Geography",
  "Mathematics",
  "Mechanical Engineering",
  "Mechanics",
  "Mechatronics Engineering",
  "Medical Laboratory Technology",
  "Medicine",
  "Metallurgy",
  "Metallurgy and Welding",
  "Meteorology",
  "Microbiology",
  "Mining Engineering",
  "Modern Physics",
  "Museology (Museum Science)",
  "Nuclear Engineering",
  "Nuclear Medicine Technology",
  "Nuclear Physics",
  "Nursing",
  "Oceanography",
  "Operation Management",
  "Operation Theater Technology",
  "Ophthalmology",
  "Pak Study",
  "Paleobotany",
  "Paleontology",
  "Paleo-Zoology",
  "Pathology",
  "Pediatrics",
  "Plasma Engineering",
  "Political Sciences",
  "Polymer Engineering",
  "Pre-Engineering",
  "Pre-Medical",
  "Printing and Graphic Arts",
  "Project Management",
  "Promotion of Health",
  "Proteomics",
  "Psychology",
  "Public Administration",
  "Public Administration (Finance)",
  "Public Finance",
  "Public Health",
  "Recreational and Performing Arts, Music",
  "Refrigeration and Air Conditioning",
  "Religious Studies",
  "Shahadat-ul-Alia",
  "Shahadat-ul-Sanvia Aama",
  "Shahadat-ul-Sanvia Khasa",
  "Shahad-ul-aalmia",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Software Project Management",
  "Space Sciences",
  "Special Education",
  "Statistics",
  "Structural Engineering",
  "Supply Chain Management",
  "Surgery and related Medical Specialties",
  "System Engineering",
  "Telecommunication Engineering",
  "Textile",
  "Textile and Management",
  "Textile Spinning",
  "Textile Weaving Technology",
  "Total Quality Management",
  "Transportation Engineering",
  "Urban Management",
  "Urdu",
  "Veterinary and Medicine",
  "Water Resource Management",
  "Zoological",
  "Zoological Sciences",
];
export const domicileOptions = [
  "Awaran",
  "Barkhan",
  "Chaghi",
  "Chaman",
  "Dera Bugti",
  "Duki",
  "Gawadar",
  "Harnai",
  "Hub",
  "Jafarabad",
  "Jhal Magsi",
  "Kachhi (Bolan)",
  "Kallat",
  "Karezat",
  "Kech (Turbat)",
  "Kharan",
  "Khuzdar",
  "Killa Abdullah",
  "Killa Saifullah",
  "Kohlu",
  "Lasbela",
  "Lehri",
  "Loralai",
  "Mastung",
  "Musa Khel",
  "Naseerabad",
  "Nushki",
  "Pishin",
  "Punjgur",
  "Quetta",
  "Sheerani",
  "Sibi",
  "Sohbatpur",
  "Surab",
  "Usta Mohammad",
  "Washuk",
  "Zhob",
  "Ziarat",
];
export const institutions = [
  // Public Sector Universities
  "University of Balochistan, Quetta",
  "Balochistan University of Information Technology, Engineering and Management Sciences (BUITEMS), Quetta",
  "Sardar Bahadur Khan Women’s University (SBKWU), Quetta",
  "Lasbela University of Agriculture, Water and Marine Sciences, Uthal",
  "Bolan Medical College, Quetta",
  "University of Turbat, Turbat",
  "University of Loralai, Loralai",
  "Balochistan Agriculture College, Quetta",
  "Nawab Ghous Bakhsh Raisani Law College, Quetta",
  "Makran Medical College, Turbat",
  "Jhalawan Medical College, Khuzdar",
  "Balochistan Residential College, Loralai",
  "Balochistan Residential College, Khuzdar",
  "Government College of Technology, Quetta",
  "Balochistan University of Engineering and Technology (BUET), Khuzdar",
  "Muslim Bagh Degree College, Killa Saifullah",
  "Government College of Education, Quetta",
  "Mir Chakar Khan Rind University, Sibi",
  "University of Gwadar, Gwadar",
  "Govt Girls Postgraduate College Quetta Cantt",
  "Board of Intermediate and Secondary Education Quetta",
  "Quaid-i-Azam University, Islamabad",
  "National University of Sciences and Technology (NUST), Islamabad",
  "Punjab University, Lahore",
  "University of Karachi, Karachi",
  "University of Engineering and Technology (UET), Lahore",
  "University of Agriculture, Faisalabad",
  "NED University of Engineering and Technology, Karachi",
  "University of Peshawar, Peshawar",
  "University of Sindh, Jamshoro",
  "Allama Iqbal Open University (AIOU), Islamabad",
  "Government College University (GCU), Lahore",
  "Government College University (GCU), Faisalabad",
  "Lahore College for Women University (LCWU), Lahore",
  "COMSATS University Islamabad (CUI)",
  "Islamia College University, Peshawar",
  "Arid Agriculture University, Rawalpindi",
  "Mehran University of Engineering and Technology, Jamshoro",
  "University of Veterinary and Animal Sciences (UVAS), Lahore",
  "Fatima Jinnah Women University (FJWU), Rawalpindi",
  "University of Gujrat, Gujrat",
  "Shaheed Benazir Bhutto University, Nawabshah",
  "Abdul Wali Khan University, Mardan",
  "Khushal Khan Khattak University, Karak",
  "Hazara University, Mansehra",
  "University of Sargodha, Sargodha",
  "Ghazi University, Dera Ghazi Khan",
  "The Women University Multan, Multan",
  "Lasbela University of Agriculture, Water and Marine Sciences, Uthal",
  "Kohat University of Science and Technology, Kohat",
  "Shaheed Benazir Bhutto Women University, Peshawar",
  "University of Malakand, Chakdara",
  "Shaheed Mohtarma Benazir Bhutto Medical University, Larkana",
  "University of Turbat, Turbat",
  "Karakoram International University, Gilgit",
  "Baltistan University, Skardu",
  "The University of Azad Jammu and Kashmir, Muzaffarabad",
  "Mirpur University of Science and Technology (MUST), Mirpur",
  "National Textile University, Faisalabad",
  "Sindh Agriculture University, Tandojam",
  "University of Swat, Mingora",
  "Abdul Wali Khan University, Mardan",

  // Private Sector Universities
  "Lahore University of Management Sciences (LUMS), Lahore",
  "Aga Khan University, Karachi",
  "National University of Computer and Emerging Sciences (FAST-NU), Islamabad",
  "Ghulam Ishaq Khan Institute of Engineering Sciences and Technology (GIKI), Swabi",
  "Beaconhouse National University (BNU), Lahore",
  "University of Management and Technology (UMT), Lahore",
  "The Superior University, Lahore",
  "Shaheed Zulfikar Ali Bhutto Institute of Science and Technology (SZABIST), Karachi",
  "Riphah International University, Islamabad",
  "Bahria University, Islamabad",
  "Habib University, Karachi",
  "Iqra University, Karachi",
  "Institute of Business Administration (IBA), Karachi",
  "Institute of Business Management (IoBM), Karachi",
  "Preston University, Islamabad",
  "The Millennium University College (TMUC), Islamabad",
  "Indus Valley School of Art and Architecture, Karachi",
  "University of Central Punjab (UCP), Lahore",
  "National College of Business Administration and Economics (NCBA&E), Lahore",
  "Greenwich University, Karachi",
  "Qarshi University, Lahore",
  "City University of Science and Information Technology, Peshawar",
  "The Islamia University of Bahawalpur, Bahawalpur",
  "Abasyn University, Peshawar/Islamabad",
  "South Asian University, Islamabad",
  "Jinnah University for Women, Karachi",
  "Capital University of Science and Technology (CUST), Islamabad",
  "Foundation University, Islamabad",
  "Minhaj University, Lahore",
  "Forman Christian College University, Lahore",

  // Medical Universities
  "Dow University of Health Sciences, Karachi",
  "King Edward Medical University, Lahore",
  "Fatima Jinnah Medical University, Lahore",
  "Liaquat University of Medical and Health Sciences, Jamshoro",
  "Khyber Medical University, Peshawar",
  "Jinnah Sindh Medical University, Karachi",
  "Rawalpindi Medical University, Rawalpindi",
  "Punjab Medical College, Faisalabad",
  "Bolan Medical College, Quetta",
  "Ayub Medical College, Abbottabad",

  // Engineering and Technology Universities
  "GIKI, Swabi",
  "UET, Lahore",
  "UET, Peshawar",
  "UET, Taxila",
  "NUST, Islamabad",
  "NED University of Engineering and Technology, Karachi",
  "Mehran University, Jamshoro",
  "Pakistan Institute of Engineering and Applied Sciences (PIEAS), Islamabad",
  "Dawood University of Engineering and Technology, Karachi",
  "Institute of Space Technology (IST), Islamabad",

  // Notable Colleges
  "Government College University, Lahore",
  "Kinnaird College for Women, Lahore",
  "Forman Christian College University, Lahore",
  "Cadet College Hasan Abdal, Attock",
  "Cadet College Petaro, Jamshoro",
  "Army Burn Hall College, Abbottabad",
  "Punjab College (various campuses)",
  "Jinnah College for Women, Peshawar",
  "Edwards College, Peshawar",
  "St. Patrick’s College, Karachi",
  "St. Joseph’s College for Women, Karachi",
  "Islamia College, Peshawar",
  "Bahria College (various campuses)",

  // Regional Universities and Colleges
  "University of Turbat",
  "Khushal Khan Khattak University, Karak",
  "Karakoram International University, Gilgit",
  "University of Swabi",
  "University of Loralai",
  "Other",
];
